HEAT-6767463: Fix users not all visible and not receiving invitation mail when registration
StadGent/laravel_site_opening-hours pull request #304
Opened 2024-11-12 16:17 UTC by jonasanne

2024-11-12 16:27 UTC, jonasanne commented
After testing this on DV I see the "registration flow" does not even work.
When using the "Gebruiker activeren" link inside the invitation mail you get a 404 so the route does not even exists...

2024-11-13 13:30 UTC, Jelle-S requested changes

2024-11-13 13:30 UTC, Jelle-S commented on app/Repositories/EloquentRepository.php
> +        $query = $this->model->take($limit)->query();
```
BadMethodCallException  Call to undefined method Illuminate\Database\Eloquent\Builder::query().
```

2024-11-13 13:45 UTC, Jelle-S approved these changes

2024-11-13 13:45 UTC, merged